services:
  - type: web
    name: pdf-to-word
    runtime: python
    buildCommand: "apt-get install -y poppler-utils tesseract-ocr && pip install -r requirements.txt"
    startCommand: "gunicorn app:app"